### ISSUE TITLE
Highway.Data with ASP.Net Identity

### ISSUE THREAD

**Issue by ghost** [HighwayFramework/Highway.Data#71]
I have used Highway.Data in previous projects and I am now starting a new project where I am using ASP.Net Identity to manage my user accounts. I noticed it creates an ApplicationDbContext, which inherits from IdentityDbContext, which inherits from DbContext. 

I would like to only use one data context and so was wondering how I can use Highway.Data with this?

Edit: To be more specific in order to merge the Identity tables with my context, my context has to inherit from IdentityDbContext. So I don't see how I can do this since my context needs to inherit from DataContext in order to us Highway.Data.

**Comment by bluefindata** [comment]
Tim,

I have posted an issue back in Jan. on github for testing async methods
with highway data and haven't heard anything back.

I wouldn't think this would be a new issue and that there would be a
solution out there, but I haven't been able to find one.

Could you please give me some direction on how to handle this? I really
like highway data, but if I can't unit test my async queries, I will have
to find an alternative. I'd rather not, because of how deeply embedded
 Highway Data is in my project.


Thank you for your time,

*Andrew J. Petersen *| (225) 317-9660
www.bluefindata.com <http://bluefindata.com>
