### ISSUE TITLE
Latest Update Breaks Queries

### ISSUE THREAD

**Issue by VirtualRichard** [HighwayFramework/Highway.Data#82]
To reproduce, just create a new Visual Studio 2013 Unit Test Project, paste in the tests from getting started and run. Tests will fail.

if you uninstall 6.0.3 and then run Install-Package Highway.Data -Version 6.0.1 in the package manager, the tests will then pass...

That's not good.

**Comment by daveh551** [comment]
My experience differs:  Copying the first test from getting started, it fails with both 6.0.3 AND with 6.0.1. This also reflects my experience in the project I'm working on: context.AsQueryable<T>() is returning an empty list regardless of what's been added to the context.

**Comment by kmcginnes** [comment]
My pull request #84 fixes this issue.

**Comment by daveh551** [comment]
Kris,

 

See pull request #86 <https://github.com/HighwayFramework/Highway.Data/pull/86> .

 

While it’s hard to argue that a fix that makes the tests pass is not “correct”, I think the true root cause for the problem is in the IsType<T1>() method of the ObjectRepresentation class.  As written, it returns “Entity.GetType() is T1”.  But GetType is a value of class System.Type, and that will never be a T1 (unless T1 is System.Type).

 

My fix is to substitute “Entity is T1”, and when that is done, all tests pass.

 

Tim/Devlin, any chance we could get this pushed out to nuget fairly quickly?

 

Thanks,

 

Dave

**Comment by kmcginnes** [comment]
@daveh551 I'd agree with you if there was some scenario where using the standard, built in linq function `OfType<T>()` does not work. In that case I'd say fix the custom function `IsType<T>()`. However, if there is not a good reason to reinvent the wheel here I say drop the use of `IsType<T>()` completely.

**Comment by DevlinLiles** [comment]
We updated this to use the Entity is T1 in the 6.0.4 package. My oversight on not seeing the stale results and thinking they were current. Thanks for the pull request.

**Comment by daveh551** [comment]
Thanks, Devlin.
